steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$_PROJECT_ID/sharelo-iframely:$_TAG",
       "--build-arg", "project_id=$_PROJECT_ID", "."]
images: ["gcr.io/$_PROJECT_ID/sharelo-iframely:$_TAG"]